### ISSUE TITLE
Build broken due to merge commit

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10741]
### What we should change and why (this is tech debt)

A recent merge commit broke the build, as the PR  #11785 was not including the changes introduced in #10696:

 All failed tests on this CI node:

```
Failures:

  1) 
    As an admin
    I want to manage product variants
 editing weight for a variant
     Failure/Error: login_as_admin_and_visit spree.admin_product_variants_path product
     
     NoMethodError:
       undefined method `login_as_admin_and_visit' for #<RSpec::ExampleGroups::AsAnAdminIWantToManageProductVariants "editing weight for a variant" (./spec/system/admin/variants_spec.rb:256)>
       Did you mean?  login_as_admin
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_admin_i_want_to_manage_product_variants_editing_weight_for_a_variant_262.png

     
     # ./spec/system/admin/variants_spec.rb:261:in `block (2 levels) in <top (required)>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <top (required)>'

  2) 
    As an admin
    I want to manage product variants
 new variant creating a new variant with non-weight unit type
     Failure/Error: login_as_admin_and_visit spree.admin_product_variants_path product
     
     NoMethodError:
       undefined method `login_as_admin_and_visit' for #<RSpec::ExampleGroups::AsAnAdminIWantToManageProductVariants::NewVariant "creating a new variant with non-weight unit type" (./spec/system/admin/variants_spec.rb:51)>
       Did you mean?  login_as_admin
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_admin_i_want_to_manage_product_variants_new_variant_creating_a_new_variant_with_non_weight_unit_type_582.png

     
     # ./spec/system/admin/variants_spec.rb:56:in `block (3 levels) in <top (required)>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <top (required)>'

Finished in 3 minutes 34.5 seconds
34 examples, 2 failures, 3 pending
```

### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/4788649135/jobs/8515533355
