### ISSUE TITLE
[Spree Upgrade] Fix reference to on_demand from products/new/replace_form.html.haml.deface 

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2689]
## Description

Our customization of the new product form still relies on the `on_demand` attribute which no longer exists. This obviously causes a 500 error as follows:

```
...
Deface: 1 overrides found for 'spree/admin/products/new'
Deface: 'replace_form' matched 0 times with 'fieldset[data-hook='new_product']'
  Rendered /home/pau/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/spree-94b1f395bbf2/backend/app/views/spree/admin/products/new.html.erb (51.2ms)
  Rendered spree/admin/products/new.js.erb (71.6ms)
Completed 500 Internal Server Error in 477.7ms (ActiveRecord: 2.7ms)
** [Bugsnag] No API key configured, couldn't notify

ActionView::Template::Error (undefined method `on_demand' for #<Spree::Product:0x0055828adc3c98>):
    1: <%# This chunk is just a copy of Spree's core/app/views/spree/admin/products/new.js.erb %>
    2: $("#new_product").html('<%= escape_javascript(render :template => "spree/admin/products/new", :formats => [:html], :handlers => [:erb]) %>');
    3: handle_date_picker_fields();
    4: <% unless Rails.env.test? %>
    5:   $('.select2').select2();
  app/views/spree/admin/products/new.js.erb:2:in `_4eaffefcc9f7b9fc61b4f6ea66083e28'


  Rendered /home/pau/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/templates/rescues/_trace.erb (79.6ms)
...
```

## Expected Behavior
`products/new` page should render successfully without errors.

## Actual Behavior
The page fails to render raising the error showed above.

## Steps to Reproduce

1. Go to `/admin/products`
2. Click on `+ NEW PRODUCT`
3. an "undefined method `on_demand' for #<Spree::Product:0x0055828adc3c98> raises"

## Possible Fix
?

**Comment by luisramos0** [comment]
this issue should be fixed by this change: https://github.com/openfoodfoundation/openfoodnetwork/issues/2870

**Comment by luisramos0** [comment]
@sauloperez can we close this one? the new product page is now failing with #2982, right?

**Comment by luisramos0** [comment]
Hmm, actually, I am not sure, how could adding "on_demand=" fix "undefined method `on_demand`" (without equals)?

**Comment by sauloperez** [comment]
I'll go first with #2982 and then I'll come back to this one. It might not be an issue anymore after we fix the former.
